namespace DD.CBU.Compute.Api.Contracts.Directory
{

	using System;
	using System.Collections.Generic;
	using System.Xml.Serialization;
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------
	// 
	// This source code was auto-generated by xsd, Version=4.6.1055.0.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
	[System.Xml.Serialization.XmlRootAttribute("createUser", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
	public partial class CreateUserType
	{

		private string userNameField;

		private string passwordField;

		private string fullNameField;

		private string firstNameField;

		private string lastNameField;

		private string emailAddressField;

		private string[] roleField;

		private PhoneType phoneField;

		private string departmentField;

		private string customDefined1Field;

		private string customDefined2Field;

		/// <remarks/>
		public string userName
		{
			get
			{
				return this.userNameField;
			}
			set
			{
				this.userNameField = value;
			}
		}

		/// <remarks/>
		public string password
		{
			get
			{
				return this.passwordField;
			}
			set
			{
				this.passwordField = value;
			}
		}

		/// <remarks/>
		public string fullName
		{
			get
			{
				return this.fullNameField;
			}
			set
			{
				this.fullNameField = value;
			}
		}

		/// <remarks/>
		public string firstName
		{
			get
			{
				return this.firstNameField;
			}
			set
			{
				this.firstNameField = value;
			}
		}

		/// <remarks/>
		public string lastName
		{
			get
			{
				return this.lastNameField;
			}
			set
			{
				this.lastNameField = value;
			}
		}

		/// <remarks/>
		public string emailAddress
		{
			get
			{
				return this.emailAddressField;
			}
			set
			{
				this.emailAddressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("role")]
		public string[] role
		{
			get
			{
				return this.roleField;
			}
			set
			{
				this.roleField = value;
			}
		}

		/// <remarks/>
		public PhoneType phone
		{
			get
			{
				return this.phoneField;
			}
			set
			{
				this.phoneField = value;
			}
		}

		/// <remarks/>
		public string department
		{
			get
			{
				return this.departmentField;
			}
			set
			{
				this.departmentField = value;
			}
		}

		/// <remarks/>
		public string customDefined1
		{
			get
			{
				return this.customDefined1Field;
			}
			set
			{
				this.customDefined1Field = value;
			}
		}

		/// <remarks/>
		public string customDefined2
		{
			get
			{
				return this.customDefined2Field;
			}
			set
			{
				this.customDefined2Field = value;
			}
		}
	}
}
